name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Run ESLint (client)
        run: npm run lint
        working-directory: client

      - name: Check Prettier formatting (client)
        run: npm run format -- --check
        working-directory: client

  build-and-test:
    name: Build & Smoke Test Server
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        run: npm ci
        working-directory: server

      - name: Run ESLint (server)
        run: npm run lint
        working-directory: server

      - name: Check Prettier formatting (server)
        run: npm run format -- --check
        working-directory: server

      - name: Smoke test server
        working-directory: server
        run: |
          node src/app/app.mjs & sleep 10
          curl --fail http://localhost:4000/health || exit 1
